-- Pilot venue geofences (Aug 2026). Generated by scripts/geofence-venue.mjs
-- (Nominatim geocode + Overpass footprint + the app's pickBestPolygon), then
-- reviewed by hand. Re-generate any time with:  node scripts/geofence-venue.mjs
--
-- Design choice per venue:
--   • Martha My Dear  → POLYGON (real OSM footprint). With the polygon-aware
--     check-in cushion (lib/sessions.ts: CHECKIN_ACCURACY_CAP_POLYGON_M = 12),
--     check-in is tight — you must be at/inside the building, not across the lot.
--     This is the venue where the "checked in from ~50 ft" complaint came from.
--   • Lost and Found / The 5 Spot → CIRCLE 35m. Jacob is demoing these live in
--     front of prospects tomorrow; a circle guarantees the check-in succeeds.
--     "Doesn't need to be precise, may be temporary" — exactly the circle case.
--   • HereNow Demo (Apple Park) → CIRCLE 120m for App Store review (see
--     apple_demo_account.sql — the demo account also bypasses the fence).
--
-- NOTE: both `center` (geography POINT) and the mirrored `center_lat`/`center_lng`
-- are set. The native background geofence (hooks/useGeofenceTask.ts) reads the
-- mirrored columns; a zone with only `center` set is invisible to auto-checkout.

-- ── Martha My Dear — attach the real footprint to the existing zone ───────────
-- osm way #1533113462 "Martha My Dear", 7 pts, footprint diagonal ~43m, the
-- geocoded point falls inside it. The geofence_hardening trigger re-validates and
-- normalizes to MULTIPOLYGON on write, so a minor winding issue self-repairs.
UPDATE zones SET
  building_polygon = ST_GeogFromText('POLYGON((-86.743558 36.1953509, -86.7435291 36.19541, -86.7434903 36.1954815, -86.7431788 36.1953781, -86.7432434 36.1952421, -86.743541 36.195345, -86.743558 36.1953509))'),
  polygon_source   = 'osm',
  polygon_wkt      = 'POLYGON((-86.743558 36.1953509, -86.7435291 36.19541, -86.7434903 36.1954815, -86.7431788 36.1953781, -86.7432434 36.1952421, -86.743541 36.195345, -86.743558 36.1953509))',
  radius_meters    = 10   -- radius is ignored once a polygon exists; keep the UI honest
WHERE name = 'Martha My Dear';

-- Verify it took (expect a MULTIPOLYGON and a small area, not the whole block):
--   SELECT name, polygon_source, round(ST_Area(building_polygon)) AS m2,
--          ST_GeometryType(building_polygon::geometry) AS gtype
--   FROM zones WHERE name = 'Martha My Dear';
-- Then sanity-check the fence with a point at the door vs across the lot:
--   SELECT user_in_zone(id, 36.1953645, -86.7433683, 12) AS at_door,      -- true
--          user_in_zone(id, 36.19570,   -86.74300,    12) AS across_lot   -- false
--   FROM zones WHERE name = 'Martha My Dear';

-- ── Lost and Found — 3104 Gallatin Pike (circle) ─────────────────────────────
INSERT INTO zones (name, description, center, center_lat, center_lng, radius_meters, is_active)
VALUES (
  'Lost and Found', NULL,
  ST_GeographyFromText('POINT(-86.7374263 36.2051208)'), 36.2051208, -86.7374263,
  35, true
)
ON CONFLICT DO NOTHING;

-- ── The 5 Spot — 1008 Forest Ave (circle) ────────────────────────────────────
INSERT INTO zones (name, description, center, center_lat, center_lng, radius_meters, is_active)
VALUES (
  'The 5 Spot', NULL,
  ST_GeographyFromText('POINT(-86.7507137 36.1785202)'), 36.1785202, -86.7507137,
  35, true
)
ON CONFLICT DO NOTHING;

-- ── HereNow Demo (Apple Park) — for App Store review (circle, generous) ───────
INSERT INTO zones (name, description, center, center_lat, center_lng, radius_meters, is_active)
VALUES (
  'HereNow Demo (Apple Park)', 'Demo venue for App Store review',
  ST_GeographyFromText('POINT(-122.008972 37.334606)'), 37.334606, -122.008972,
  120, true
)
ON CONFLICT DO NOTHING;
