-- Pilot venue geofences (Aug 2026). Generated by scripts/geofence-venue.mjs
-- (Nominatim geocode + Overpass footprint + the app's pickBestPolygon), then
-- reviewed by hand. Re-generate any time with:  node scripts/geofence-venue.mjs
--
-- Design choice per venue:
--   • Martha My Dear  → POLYGON (real OSM footprint). With the polygon-aware
--     check-in cushion (lib/sessions.ts: CHECKIN_ACCURACY_CAP_POLYGON_M = 12),
--     check-in is tight — you must be at/inside the building, not across the lot.
--     This is the venue where the "checked in from ~50 ft" complaint came from.
--   • Lost and Found → CIRCLE 120m. Open-air food-truck lot, so patrons gather
--     past a tight circle around the street-address pin; keep the radius generous.
--     "Doesn't need to be precise, may be temporary" is exactly this case.
--   • The 5 Spot → CIRCLE 35m (indoor room; the address pin sits on the building).
--   • HereNow Demo (Apple Park) → CIRCLE 120m for App Store review (see
--     apple_demo_account.sql — the demo account also bypasses the fence).
--
-- NOTE: both `center` (geography POINT) and the mirrored `center_lat`/`center_lng`
-- are set. The native background geofence (hooks/useGeofenceTask.ts) reads the
-- mirrored columns; a zone with only `center` set is invisible to auto-checkout.

-- ── Martha My Dear — attach the real footprint to the existing zone ───────────
-- osm way #1533113462 "Martha My Dear", 7 pts, footprint diagonal ~43m, the
-- geocoded point falls inside it. The geofence_hardening trigger re-validates and
-- normalizes to MULTIPOLYGON on write, so a minor winding issue self-repairs.
UPDATE zones SET
  building_polygon = ST_GeogFromText('POLYGON((-86.743558 36.1953509, -86.7435291 36.19541, -86.7434903 36.1954815, -86.7431788 36.1953781, -86.7432434 36.1952421, -86.743541 36.195345, -86.743558 36.1953509))'),
  polygon_source   = 'osm',
  polygon_wkt      = 'POLYGON((-86.743558 36.1953509, -86.7435291 36.19541, -86.7434903 36.1954815, -86.7431788 36.1953781, -86.7432434 36.1952421, -86.743541 36.195345, -86.743558 36.1953509))',
  radius_meters    = 10   -- radius is ignored once a polygon exists; keep the UI honest
WHERE name = 'Martha My Dear';

-- Verify it took (expect a MULTIPOLYGON and a small area, not the whole block):
--   SELECT name, polygon_source, round(ST_Area(building_polygon)) AS m2,
--          ST_GeometryType(building_polygon::geometry) AS gtype
--   FROM zones WHERE name = 'Martha My Dear';
-- Then sanity-check the fence with a point at the door vs across the lot:
--   SELECT user_in_zone(id, 36.1953645, -86.7433683, 12) AS at_door,      -- true
--          user_in_zone(id, 36.19570,   -86.74300,    12) AS across_lot   -- false
--   FROM zones WHERE name = 'Martha My Dear';

-- ── Lost and Found — 3104 Gallatin Pike (circle) ─────────────────────────────
-- zones.name has no unique constraint, so ON CONFLICT DO NOTHING is a no-op that
-- would mint a duplicate on re-run. Upsert by name: UPDATE if present, INSERT if
-- missing. building_polygon forced NULL so the reliable circle path is used, and
-- the radius is generous because this is an open-air lot.
UPDATE zones SET
  center           = ST_GeographyFromText('POINT(-86.7374263 36.2051208)'),
  center_lat       = 36.2051208,
  center_lng       = -86.7374263,
  radius_meters    = 120,
  is_active        = true,
  building_polygon = NULL
WHERE name = 'Lost and Found';
INSERT INTO zones (name, description, center, center_lat, center_lng, radius_meters, is_active)
SELECT 'Lost and Found', NULL,
       ST_GeographyFromText('POINT(-86.7374263 36.2051208)'), 36.2051208, -86.7374263,
       120, true
WHERE NOT EXISTS (SELECT 1 FROM zones WHERE name = 'Lost and Found');

-- ── The 5 Spot — 1008 Forest Ave (circle) ────────────────────────────────────
UPDATE zones SET
  center           = ST_GeographyFromText('POINT(-86.7507137 36.1785202)'),
  center_lat       = 36.1785202,
  center_lng       = -86.7507137,
  radius_meters    = 35,
  is_active        = true,
  building_polygon = NULL
WHERE name = 'The 5 Spot';
INSERT INTO zones (name, description, center, center_lat, center_lng, radius_meters, is_active)
SELECT 'The 5 Spot', NULL,
       ST_GeographyFromText('POINT(-86.7507137 36.1785202)'), 36.1785202, -86.7507137,
       35, true
WHERE NOT EXISTS (SELECT 1 FROM zones WHERE name = 'The 5 Spot');

-- ── HereNow Demo (Apple Park) — for App Store review (circle, generous) ───────
UPDATE zones SET
  center        = ST_GeographyFromText('POINT(-122.008972 37.334606)'),
  center_lat    = 37.334606,
  center_lng    = -122.008972,
  radius_meters = 120,
  is_active     = true
WHERE name = 'HereNow Demo (Apple Park)';
INSERT INTO zones (name, description, center, center_lat, center_lng, radius_meters, is_active)
SELECT 'HereNow Demo (Apple Park)', 'Demo venue for App Store review',
       ST_GeographyFromText('POINT(-122.008972 37.334606)'), 37.334606, -122.008972,
       120, true
WHERE NOT EXISTS (SELECT 1 FROM zones WHERE name = 'HereNow Demo (Apple Park)');
